#!/usr/bin/env bash

NUMBER="$(pkexec env DISPLAY="$DISPLAY" XAUTHORITY="$XAUTHORITY" KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true "$PWD"/number_root.run "$HOME")"
IDANDROID=$"ID do Android:"
IDANDROIDERRO=$"Não foi possível resgatar o ID do Android. \n\nAtenção: Waydroid precisa estar aberto."

if [[ -n "$NUMBER" ]]; then
	kdialog --inputbox "$IDANDROID" "$NUMBER" --title "Android ID"
else
	kdialog --msgbox "$IDANDROIDERRO" --title "Android ID"
fi
