#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Configurar o AppimageLauncher"
COMMENT=$"Escolher o comportamento dos programas disponibilizados em .appimage"
CATEGORY="System"
