#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Qt Assistant"
COMMENT=$"Programas de desenvolvimento para QT."
ICON="icons/assistant.png"
CATEGORY="Desenv"
