#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter


NAME=$"Procurar servidores (zeroconf)"
#COMMENT=$"Uma rede de configuração zero é uma rede IP configurada sem usar nenhuma configuração manual ou servidores de configuração."
ICON="icons/icon_find-server-zeroconf.png"
CATEGORY="Server"
