#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

COMMENT=$"Utilitário que facilita a restauração do sistema instalado,
<br>
principalmente a restauração do boot do sistema (Grub).
<br><br>
Também pode ser utilizado para acessar o gerenciador
<br>
de pacotes e o terminal do sistema instalado."
CATEGORY="System Star"
