#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter


NAME=$"Temas, Desktop e Ajustes"
COMMENT=$"Disponiblizamos configurações completas para você selecionar de forma extremamente simples."
CATEGORY="Personalization"
ICON="icons/icon-aparencia-desempenho-usabilidade.png"
