#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter


NAME=$"Restaurar a configuração de programas"
COMMENT=""
CATEGORY="System"
ICON="icons/icon-restaurar-configuracoes.png"
