#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Bluetooth"
COMMENT=$"Configurações gerais de dispositivos bluetooth."
CATEGORY="Hardware"
EXEC="kcmshell5 bluedeviladapters bluedevildevices bluedevilglobal"
