#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

EXEC="brightness-controller"
CATEGORY="Hardware"
COMMENT=$"Controle o brilho e as cores"
NAME=$"Brilho e cor"
ICON="icons/brightness-adjust.svg"
