#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Qt Designer"
COMMENT=$"Programas de desenvolvimento para QT."
ICON="icons/QtProject-designer.png"
CATEGORY="Desenv"
