#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Particionar ou formatar"
COMMENT=$"Cuidado, este programa poderá apagar todos os dados do computador."
CATEGORY="System"
ICON="icons/gparted.png"
