#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Informações de armazenamento (SMART)"
ICON="/usr/share/icons/hicolor/128x128/apps/gsmartcontrol.png"
CATEGORY="About"
