#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Firewall"
COMMENT=$"Configurar regras de segurança para a conexão com a internet."
CATEGORY="Privacy"
ICON="icons/gufw.png"
