#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter
c_user=$(whoami)

NAME=$"Firewall"
COMMENT=$"Configurar regras de segurança para a conexão com a internet."
CATEGORY="Privacy"
ICON="icons/gufw.png"
EXEC="pkexec /usr/bin/gufw-pkexec $c_user"
