#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

CATEGORY="Hardware"
NAME=$"Configurar webcam ou placa de captura"
ICON="icons/icon_webcam.png"
COMMENT=""
