#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Joystick"
#COMMENT=$"Acesse seus arquivos que estão no Google Drive ou ownCloud diretamente no gerenciador de arquivos."
#ICON="icons/kcm_kaccounts.png"
CATEGORY="Hardware"
