#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

#NAME=$"Integração com Google Drive e ownCloud"
COMMENT=$"Lembre que ativar esse sistema de pesquisa aumenta<br>o consumo de memória e processamento do sistema."
CATEGORY="Personalization"
