#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

#NAME=$"Localizações"
EXEC="kcmshell5 desktoppaths"
ICON="icons/icon_find-localizacoes-directory.png"
CATEGORY="Personalization" 
