#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

EXEC="kcmshell5 msm_timedate clock"
CATEGORY="Language"
COMMENT=$"Ajuste a data, hora e fuso horário."
