#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Sessões (login e logout)"
COMMENT=$"Defina configurações de login e logout"
CATEGORY="Personalization"
EXEC="kcmshell5 kcm_smserver"
 
