#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

EXEC="kcmshell5 kcm_printer_manager"
NAME=$"Impressoras"
COMMENT=$"Instalar, configurar ou remover impressoras."
ICON="icons/icon_print.png"
CATEGORY="Star Hardware"
