#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

EXEC="kcmshell5 kcm_networkmanagement"
NAME=$"Gerenciar conexões"
COMMENT=$"Configuração avançada de rede (VPN, wifi, cabeada, IP fixo, PPPoE, ADSL, rede com fio, banda larga móvel e outros)."
ICON="icons/icon_gerenciar-conexoes.png"
CATEGORY="Network"
