#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

EXEC="kcmshell5 kcm_kscreen kcm_nightcolor kgamma kwintouchscreen kwinscreenedges"
CATEGORY="Hardware"
