#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

#NAME=$"Sessões login e logout"
#COMMENT=$"Defina configurações de login e logout"
EXEC="kcmshell5 kcm_smserver"
ICON="icons/icon_sessao-area-de-trabalho.png"
CATEGORY="Personalization" 
