#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Áreas de trabalho virtuais e atividades"
EXEC="kcmshell5 kcm_kwin_virtualdesktops kcm_activities"
COMMENT=$"Crie mais de uma área de trabalho vitual alternando entre elas."
CATEGORY="Personalization"
