#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

CATEGORY="Personalization"
EXEC="kcmshell5 kwinactions kwinadvanced kwinfocus kwinmoving kwinoptions kwinrules kwinscripts kwintabbox"
