#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

NAME=$"Qt Linguist"
COMMENT=$"Programas de desenvolvimento para QT."
ICON="icons/linguist.png"
CATEGORY="Desenv"
