#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter


NAME=$"Gerenciador de usuários"
COMMENT=$"Adiciona, remove ou edita usuários e grupos do sistema."
ICON="icons/preferences-system-users.png"
CATEGORY="System"
