#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter


NAME=$"Qt QDBusViewer "
COMMENT=$"Programas de desenvolvimento para QT."
ICON="icons/qdbusviewer.png"
CATEGORY="Desenv"
