#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

CATEGORY="Language"
EXEC="kcmshell5 regionandlang msm_language_packages formats translations"
ICON="icons/icon-multiple-language.svg"

