#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter

EXEC="systemsettings"
NAME=$"Centro de controle do KDE"
COMMENT=""
CATEGORY="System"
ICON="icons/systemsettings.png"
