#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=bigcontrolcenter


NAME=$"Configurador avançado de energia"
COMMENT=""
ICON="icons/power-manager.png"
CATEGORY="Hardware"
